This PR  fixes #  The what is swarm page on bee-docs
ethersphere/bee-docs pull request #520
Opened 2023-11-08 10:01 UTC by erickNjuki

1. Paraphrased the underlay network , overlay network and the  different layers.
2. Removed some words on first sentences in order avoid repetition.
3. Introduced un-ordered list. it is good practice to differentiate the lists.
4. Also made grammatical corrections.

2023-11-09 07:54 UTC, bennehc reviewed
Removed repetition on first sentences

I dont think  this change is needed.  Currently it reads well and provides more context.

2023-11-16 07:53 UTC, NoahMaizels commented on docs/learn/technology/what-is-swarm.md
> +Swarm serves as an underlay transport by establishing connections between nodes in the network and routing data between them. This provides a low-level communication channel that enables nodes to com
Swarm includes both underlay and overlay, so it is not really accurate to say that Swarm itself serves as an underlay transport. It includes both these layers.

2023-11-16 07:54 UTC, NoahMaizels commented on docs/learn/technology/what-is-swarm.md
> +Swarm is an overlay network with protocols powering the [Distributed Immutable Store of Chunks (DISC)](/docs/learn/technology/DISC/). This layer is responsible for storing and retrieving data in a de
Same issue as above about underlay, Swarm is not an overlay network, Swarm _includes_ an overlay network

2023-11-16 07:57 UTC, NoahMaizels commented on docs/learn/technology/what-is-swarm.md
> +Swarm is a component that provides high-level data access and defines APIs for base-layer features. This layer is responsible for providing an easy-to-use interface for developers to interact with Sw
Same issue as the other two sections, Swarm _includes_ a component, it is not the component itself

2023-11-16 07:58 UTC, NoahMaizels requested changes
A lot of the wording edits look good and thank you for correcting the typo! There are some conceptual problems with how the layers are described, if you can refer to the comments I left and address those it would be great!

2024-01-05 08:15 UTC, NoahMaizels commented
Haven't received a response to my comments for several weeks so I'm closing this PR

2024-01-05 08:15 UTC, closed without merging